### ISSUE TITLE
Illegal Invocation from createClock

### ISSUE THREAD

**Issue by dpogue** [sinonjs/lolex#170]
Just updated lolex and started getting a bunch of test failures with this error:

```
TypeError: Illegal invocation
  at webpack:///node_modules/lolex/lolex.js:746:0 <- webpack.tests.js:77738:52
  at Array.forEach (<anonymous>)
  at createClock (webpack:///node_modules/lolex/lolex.js:745:0 <- webpack.tests.js:77737:18)
  at Object.install (webpack:///node_modules/lolex/lolex.js:796:0 <- webpack.tests.js:77788:21)
  at ./node_modules/sinon/lib/sinon/util/fake_timers.js.exports.useFakeTimers (webpack:///node_modules/sinon/lib/sinon/util/fake_timers.js:29:0 <- webpack.tests.js:125808:21)
  at Sandbox.useFakeTimers (webpack:///node_modules/sinon/lib/sinon/sandbox.js:310:0 <- webpack.tests.js:123807:46)
```

Tests are being run in Chrome 68 headless.

**Comment by fatso83** [comment]
Not good. Thanks for reporting! Which version worked? Any reproducible code? Hard to dig into without a test case.

**Comment by dpogue** [comment]
It looks like both 2.4.0 and 2.4.1 are broken, but 2.3.2 works.

It seems to happen as soon as a test calls `sinon.useFakeTimers()`

**Comment by mantoni** [comment]
This also looks like the issue I addressed here: https://github.com/sinonjs/lolex/pull/162/files

I also ran into this when trying to run the lolex tests in headless chrome.

**Comment by SimenB** [comment]
Yeah, I think it's the same as #162 and #167

**Comment by mermaid** [comment]
This started happening to me yesterday as well. I get `TypeError: Illegal invocation` in headless chrome (and normal chrome as well) as soon as we try to use fake Timers

**Comment by barcicki** [comment]
Versions 2.4.0 and 2.4.1 also don't work on Firefox.

You can see it in build result: https://travis-ci.org/sinonjs/lolex/jobs/376426623#L2348

**Comment by fatso83** [comment]
Fixed by #162. Released as 2.4.2.

**Comment by akihikodaki** [comment]
I'm worrying I may have done something wrong as other people say it is fixed, but it still doesn't work for me. I ran a minimal code on console to reproduce the issue to make sure my NPM installation does not affect the result:
```JavaScript
navigator.userAgent
// Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
const value = Object.create(performance);
Object.getOwnPropertyNames(window.Performance.prototype)
// (17) ["timeOrigin", "onresourcetimingbufferfull", "timing", "navigation", "memory", "now", "getEntries", "getEntriesByType", "getEntriesByName", "clearResourceTimings", "setResourceTimingBufferSize", "mark", "clearMarks", "measure", "clearMeasures", "toJSON", "constructor"]
Object.getOwnPropertyDescriptor(Performance.prototype, 'mark').writable
// true
value.mark = Performance.prototype.mark;
Object.defineProperty(window, 'performance', { writable: false, value });
performance.mark('foo');
// VM130:1 Uncaught TypeError: 'Illegal invocation'
```

Can anyone confirm this, or point out a mistake?

**Comment by TeaSeaLancs** [comment]
Confirmed, this is still broken on my build as of Sinon release 6.1.5, which is running lolex 2.7.1.

**Comment by TeaSeaLancs** [comment]
Just to clarify my confirmation as well, this is occurring in Chrome and Headless Chrome.

**Comment by fatso83** [comment]
The comments on this still being a thing probably point to #200, which a PR I sent in is about to close (hopefully). Closing this while keeping #200 open, as I suspect some comments are basically duplicates.
